version: 2
jobs:
  build:
    docker:
      - image: chromedp/chromium-builder
        environment:
          TAR_OPTIONS: --no-same-owner
    steps:
      - checkout
      - run: whoami
      - run: ls -lha /usr/bin/python
      - run: 
         command: mkdir chromium
         working_directory: /root/project
      - run: 
         command: fetch --nohooks --no-history chromium
         working_directory: /root/project/chromium
      - run:
         command: gclient runhooks
         working_directory: /root/project/chromium/src
      - run:
         command: gn gen out/Release --args="is_component_build=true is_debug=false enable_nacl=false symbol_level=0 remove_webcore_debug_symbols=true"
         working_directory: /root/project/chromium/src
      - run:
         command: autoninja -C out/Release chrome -j 4
         working_directory: /root/project/chromium/src
      - run:
         command: gn gen out/Debug --args="is_component_build=true is_debug=true enable_nacl=false"
         working_directory: /root/project/chromium/src
      - run:
         command: autoninja -C out/Debug chrome -j 4
         working_directory: /root/project/chromium/src
