version: 2
jobs:
  build:
    docker:
      - image: chromedp/chromium-builder
    steps:
      - checkout
      - run: chown -R $USER:$USER /depot_tools
      - run: 
         command: mkdir chromium
         working_directory: /root/project
      - run: 
         command: fetch --nohooks --no-history chromium
         working_directory: /root/project/chromium
      - run:
         command: gclient runhooks
         working_directory: /root/project/chromium/src
      - run:
         command: gn gen out/Default
         working_directory: /root/project/chromium/src
      - run:
         command: autoninja -C out/Default chrome
         working_directory: /root/project/chromium/src
