version: 2
jobs:
  build:
    docker:
      - image: chromedp/chromium-builder
    steps:
      - checkout
      - run: cd ~
      - run: mkdir chromium
      - run: cd chromium
      - run: fetch --nohooks chromium
      - run: cd src 
      - run: gclient runhooks
      - run: gn gen out/Default
      - run: autoninja -C out/Default chrome
